### PR TITLE
Add f.json 

### PR DESCRIPTION
**Pull request by aaronzshey**
## Description

I've added f.json, which provides the "flex" property in CSS.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ x ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Verified that added/modified attribues are properly loading on browsing
- [x] Verified that added/modified attribues editing templates are properly rendered
- [x] Verified the output on changes
- [x] Verified the deployment

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas. If applicable.
- [x] I have made corresponding changes to the documentation. If applicable.
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by koustov** [comment]
@CarlyRaeJepsenStan the linked issue to implement all (no subset) attributes starts with F. So please complete all attributes that start with F and create the PR, till then you might want to keep this PR in `draft` mode.

**Comment by koustov** [comment]
By mistake closed the PR. My comment is given above.

**Comment by aaronzshey** [comment]
Thanks!  I'll work on adding font too.  Do I also have to add the sub-attributes like font-face, flex-wrap etc?

**Comment by koustov** [comment]
> Thanks! I'll work on adding font too. Do I also have to add the sub-attributes like font-face, flex-wrap etc?

yes, any CSS attribute name that starts with F needs to be implemented as part of this issue.

**Comment by koustov** [comment]
> > Thanks! I'll work on adding font too. Do I also have to add the sub-attributes like font-face, flex-wrap etc?
> 
> yes, any CSS attribute name that starts with F needs to be implemented as part of this issue.

Any update on this PR @CarlyRaeJepsenStan ?

**Comment by aaronzshey** [comment]
Nope, feel free to un-assign me.  I've been extremely busy lately and am
not sure I'll have time to finish this.

**Pull request closed without merging**
